macro(exec_cfg WORKING_DIR FLAG OUTPUT_VAR)
    execute_process(COMMAND "./llvm-config" "--${FLAG}" WORKING_DIRECTORY ${WORKING_DIR} OUTPUT_VARIABLE ${OUTPUT_VAR} OUTPUT_STRIP_TRAILING_WHITESPACE)
endmacro()
